### ISSUE TITLE
whats_new plugin: error when packages get

### ISSUE THREAD

**Issue by enricobenedos** [AppleEducate/plugins#41]
When I try to add the flutter_whatsnew (v:0.3.0) package to my project (SKD version: 1.5.4) dependencies I receive this error:

```
PS myApp> flutter packages get
Invalid argument(s): Minimum version ("1.0.0") must be less than maximum ("1.0.0-0").
package:pub_semver/src/version_range.dart 67:7                            new VersionRange
package:pub/src/solver/reformat_ranges.dart 61:27                         _reformatTerm
package:pub/src/solver/reformat_ranges.dart 39:26                         reformatRanges.<fn>
dart:_internal                                                            ListIterable.toList
package:pub/src/solver/reformat_ranges.dart 40:12                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                         reformatRanges
package:pub/src/solver/version_solver.dart 308:24                         VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 131:27                         VersionSolver._propagate
package:pub/src/solver/version_solver.dart 96:9                           VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                         resolveVersions.<fn>
package:pub/src/log.dart 378:18                                           progress
package:pub/src/solver.dart 32:10                                         resolveVersions
package:pub/src/entrypoint.dart 203:24                                    Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                    GetCommand.run
package:args/command_runner.dart 194:27                                   CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                                PubCommandRunner.runCommand.<fn>
dart:async                                                                new Future.sync
package:pub/src/utils.dart 109:12                                         captureErrors.<fn>
dart:async                                                                runZoned
package:pub/src/utils.dart 126:5                                          captureErrors
package:pub/src/command_runner.dart 171:13                                PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                                PubCommandRunner.run
===== asynchronous gap ===========================
C:\b\s\w\ir\k\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run
    pub --trace '--verbosity=warning' get --no-precompile
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter packages get" in mes-mobile-flutter...
pub get failed (1)
```

This is my pubspec.yaml:

```
name: myapp_flutter
description: My app

version: 0.4.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  intl: 0.15.7
  local_auth: 0.3.1
  random_string: ^0.0.2
  shared_preferences: ^0.5.1+1
  queries: ^0.1.9
  flutter_markdown: ^0.2.0
  xml: ^3.3.0
  #cached_network_image: ^0.7.0
  flutter_advanced_networkimage: ^0.4.15
  photo_view: ^0.3.1
  percent_indicator: ^1.0.16
  rxdart: ^0.22.0
  flutter_whatsnew: ^0.3.0
  package_info: ^0.4.0+3

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:

  ios: true
  android: "launcher_icon"
  image_path: "assets/launcher/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_white.png
    - assets/app_logo.png
    - assets/changelog.md
```
